pathvars:
  input_loc: "static/_04_temp/snakemake/0_50"
  output_loc: "static/_04_temp/snakemake/0_50" # TODO change to match others..

  models_loc: "static/_03_models/snakemake/0_50"
## start and stop
start_ix: 0
num_items: 50
